### PR TITLE
Update page classes so we can use newer version of PF-next

### PR DESCRIPTION
**Pull request by karelhala**
No UI changes, this will take effect after we merge PF update in chrome.

### CODE REVIEW

**Comment by karelhala** [comment]
ping @lgalis @Hyperkid123

**Comment by Hyperkid123** [comment]
@karelhala duplicate https://github.com/ManageIQ/service_portal-ui/pull/81 :wink:

**Comment by karelhala** [comment]
Ooh, did not noticed. Closing.

**Comment by Hyperkid123** [comment]
np

**Pull request closed without merging**
