### PR TITLE
[WIP] Update for generated swagger API client code

### PR DESCRIPTION
**Pull request by lgalis**
Update for generated swagger API client code

### CODE REVIEW

**Comment by lgalis** [comment]
@gmcculloug , or @syncrou  - this is just the updated swagger api client code  - regenerated - please merge when you can.

**Comment by lgalis** [comment]
The code was regenerated the code and the folder renamed as well.

**Comment by gmcculloug** [comment]
@lgalis Until we figure out exact where we are going to store the auto-generated clients maybe you can do something similar to what @mkanoor setup here: https://github.com/ManageIQ/service_portal-api/blob/master/Gemfile#L31

Then updating the client does not have to directly effect this repo.  Thoughts?

**Comment by lgalis** [comment]
Agree - an npm package is planned for this - once the current API PRs are merged.

**Comment by lgalis** [comment]
Closing - removed the client auto-generated api code to separate repos.

**Pull request closed without merging**
